from enum import StrEnum


class ReasonCode(StrEnum):
    INSUFFICIENT_INVENTORY = "INSUFFICIENT_INVENTORY"
    EXCESS_INVENTORY = "EXCESS_INVENTORY"
    HIGH_DEMAND = "HIGH_DEMAND"
    LOW_DEMAND = "LOW_DEMAND"
    OPEN_PO_EXISTS = "OPEN_PO_EXISTS"
    SUPPLIER_MOQ = "SUPPLIER_MOQ"
    SUPPLIER_LEAD_TIME = "SUPPLIER_LEAD_TIME"
    BUDGET_CONSTRAINT = "BUDGET_CONSTRAINT"
    STORAGE_CONSTRAINT = "STORAGE_CONSTRAINT"
    SUPPLIER_UNRELIABILITY = "SUPPLIER_UNRELIABILITY"
    FORECAST_ANOMALY = "FORECAST_ANOMALY"
    DUPLICATE_ORDER_RISK = "DUPLICATE_ORDER_RISK"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    SUPPLIER_DATA_INCOMPLETE = "SUPPLIER_DATA_INCOMPLETE"
    SUPPLIER_CAPACITY_SHORTFALL = "SUPPLIER_CAPACITY_SHORTFALL"
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    DEMAND_COVERAGE = "DEMAND_COVERAGE"
    TARGET_STOCK_POLICY = "TARGET_STOCK_POLICY"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    MOQ_INFEASIBLE = "MOQ_INFEASIBLE"
